# Generated by Django 4.2.4 on 2023-08-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
