# Generated by Django 4.2.4 on 2023-08-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valid', '0002_rename_name_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
