# Generated by Django 4.2.4 on 2023-08-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valid', '0003_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
